In [10]:
import pandas as pd

In [13]:
df = pd.read_csv("/home/asevlad/program_files/github_asevlad/lob-dex-wash-trading-paper/output_PREPARED/wash_trades_summary_multiple_windows.csv")
dfp = pd.read_csv("/home/asevlad/program_files/github_asevlad/lob-dex-wash-trading-paper/output_PREPARED_t/wash_trades_summary_multiple_windows.csv")

In [8]:
df["total_amount_wash"].sum(), dfp["total_amount_wash"].sum()

(np.float64(78.76999980211266), np.float64(12326.24995345063))

In [14]:
df["total_amount_wash"].sum(), dfp["total_amount_wash"].sum()

(np.float64(10533.159958729517), np.float64(12326.24995345063))

In [9]:
df

,scc_hash,token,window_size,time,num_wash_trades,num_trades,total_amount_wash,total_amount,total_amount_dollar_wash,total_amount_dollar
0,1193186217,AVAX,3600,"[1742637600,1742641200)",0,10,0.0,291.390000,0.0,291.390000
1,1193186217,AVAX,3600,"[1742641200,1742644800)",0,27,0.0,87.330000,0.0,87.330000
2,1193186217,AVAX,3600,"[1742644800,1742648400)",0,39,0.0,488.359994,0.0,488.359994
3,1193186217,AVAX,3600,"[1742648400,1742652000)",0,39,0.0,42.960000,0.0,42.960000
4,1193186217,AVAX,3600,"[1742652000,1742655600)",0,18,0.0,100.599997,0.0,100.599997
...,...,...,...,...,...,...,...,...,...,...
784,1190462656,AVAX,86400,"[1743379200,1743465600)",0,93,0.0,2207.479988,0.0,2207.479988
785,1190462656,AVAX,86400,"[1743465600,1743552000)",0,126,0.0,2003.489973,0.0,2003.489973
786,1190462656,AVAX,86400,"[1743552000,1743580075]",0,53,0.0,352.940002,0.0,352.940002
787,1190462656,AVAX,604800,"[1742601600,1743206400)",0,1061,0.0,6528.769985,0.0,6528.769985
788,1190462656,AVAX,604800,"[1743206400,1743580075]",0,656,0.0,7443.259972,0.0,7443.259972

In [10]:
dfp

,scc_hash,token,window_size,time,num_wash_trades,num_trades,total_amount_wash,total_amount,total_amount_dollar_wash,total_amount_dollar
0,1354930670,AVAX,3600,"[1742637600,1742641200)",2,10,1.750000,291.390000,1.750000,291.390000
1,1354930670,AVAX,3600,"[1742641200,1742644800)",4,27,5.900000,87.330000,5.900000,87.330000
2,1354930670,AVAX,3600,"[1742644800,1742648400)",12,39,10.770000,488.359994,10.770000,488.359994
3,1354930670,AVAX,3600,"[1742648400,1742652000)",0,39,0.000000,42.960000,0.000000,42.960000
4,1354930670,AVAX,3600,"[1742652000,1742655600)",0,18,0.000000,100.599997,0.000000,100.599997
...,...,...,...,...,...,...,...,...,...,...
779,1180119727,AVAX,86400,"[1743379200,1743465600)",17,68,18.240000,2136.779989,18.240000,2136.779989
780,1180119727,AVAX,86400,"[1743465600,1743552000)",25,85,227.109999,1963.329973,227.109999,1963.329973
781,1180119727,AVAX,86400,"[1743552000,1743580075]",2,35,1.700000,241.540004,1.700000,241.540004
782,1180119727,AVAX,604800,"[1742601600,1743206400)",189,252,3267.169990,4390.019992,3267.169990,4390.019992
783,1180119727,AVAX,604800,"[1743206400,1743580075]",215,253,4424.509969,5749.589969,4424.509969,5749.589969

## TEST Examples

In [2]:
import datetime
datetime.datetime.now() + datetime.timedelta(seconds=1)

datetime.datetime(2025, 11, 14, 13, 26, 14, 647077)

In [3]:
import pandas as pd

records = [
    ["A", "B"],
    ["B", "C"],
    ["C", "A"],
    ["A", "B"],
    ["B", "C"],
    ["C", "A"],
    ["A", "B"],
    ["B", "C"],
    ["C", "A"],
    ["A", "B"],
    ["B", "C"],
    ["C", "A"],
    ["A", "B"],
    ["B", "C"],
    ["C", "A"],
    ["A", "B"],
    ["B", "C"],
    ["C", "A"],

    ["B", "A"],
    ["A", "K"],
    ["K", "B"],
    ["B", "A"],
    ["A", "K"],
    ["K", "B"],
    ["B", "A"],
    ["A", "K"],
    ["K", "B"],
    ["B", "A"],
    ["A", "K"],
    ["K", "B"],
    ["B", "A"],
    ["A", "K"],
    ["K", "B"],
    ["B", "A"],
    ["A", "K"],
    ["K", "B"],

    ["D", "E"],
    ["E", "D"],
]

df_test = pd.DataFrame(records, columns=["seller", "buyer"])
for seller_id, seller in enumerate(["A", "B", "C", "K", "D", "E"]):

    df_test.seller = df_test.seller.str.replace(seller, f"{seller_id}")
    df_test.buyer = df_test.buyer.str.replace(seller, f"{seller_id}")

df_test.seller = df_test.seller.astype(int)
df_test.buyer = df_test.buyer.astype(int)
df_test = df_test.reset_index().rename(columns={"index": "time"})
df_test["price"] = 10
df_test["size"] = 10
df_test["time"] = df_test.time.apply(lambda x: datetime.datetime.now() + datetime.timedelta(seconds=x))

In [5]:
df_test.to_csv("testpy.csv", index=False)

In [11]:
from src.DataReformator import prepare_postmerge_csv

prepare_postmerge_csv(
    df_test,
    out_csv="test.csv",
    token_id="AVAX",
    token_usd_const=30,     # constant token USD price (your quick method)
    eth_usd_const=3500.0,     # optional: to also compute token_price_in_eth & trade_amount_eth
    price_is_token_in_eth=False,  # set True only if you want to take per-row df['price'] as token-in-ETH
)

Saved prepared post-merge trades to: test.csv

/home/asevlad/program_files/github_asevlad/lob-dex-wash-trading-paper/src/DataReformator.py:55: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  df["timestamp"] = (df["time"].view("int64") // 10**9).astype("int64")

In [5]:
# compatibility

In [6]:
from src.data_handler import CoinDataStore
from src.DataReformator import prepare_postmerge_csv

token = "AVAX"
store = CoinDataStore(token, engine="fastparquet")
df_trades = store.load_all()

prepare_postmerge_csv(
    df_trades,
    out_csv=f"{token}_compatible_trades.csv",
    token_id=token,
    token_usd_const=1,     # constant token USD price (your quick method)
    eth_usd_const=3500.0,     # optional: to also compute token_price_in_eth & trade_amount_eth
    price_is_token_in_eth=False,  # set True only if you want to take per-row df['price'] as token-in-ETH
)

/home/asevlad/program_files/github_asevlad/lob-dex-wash-trading-paper/src/DataReformator.py:55: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  df["timestamp"] = (df["time"].view("int64") // 10**9).astype("int64")

KeyboardInterrupt: