In [ ]:


import pandas as pd

In [ ]:
df = pd.read_csv("/home/asevlad/program_files/github_asevlad/lob-dex-wash-trading-paper/output_PREPARED/wash_trades_summary_multiple_windows.csv")

In [32]:
df["total_amount_wash"].sum(), df["total_amount"].sum()

(np.int64(100), np.int64(100))

In [33]:
df["total_amount_wash"].sum() / df["total_amount"].sum()

np.float64(1.0)

In [34]:
df

,scc_hash,token,window_size,time,num_wash_trades,num_trades,total_amount_wash,total_amount,total_amount_dollar_wash,total_amount_dollar
0,1109781897,AVAX,3600,"[1760454000,1760454935]",10,10,100,100,3000,3000

In [35]:
df

,scc_hash,token,window_size,time,num_wash_trades,num_trades,total_amount_wash,total_amount,total_amount_dollar_wash,total_amount_dollar
0,1109781897,AVAX,3600,"[1760454000,1760454935]",10,10,100,100,3000,3000

## TEST Examples

In [26]:
import datetime
datetime.datetime.now() + datetime.timedelta(seconds=1)

datetime.datetime(2025, 10, 14, 15, 14, 34, 649618)

In [28]:
import pandas as pd

records = [
    ["A", "B"],
    ["B", "A"],
    ["A", "B"],
    ["B", "A"],
    ["A", "B"],
    ["B", "A"],
    ["A", "B"],
    ["B", "A"],
    ["A", "B"],
    ["B", "A"],

    ["B", "C"],
    ["C", "A"],

    ["D", "E"],
    ["E", "D"],
]

df_test = pd.DataFrame(records, columns=["seller", "buyer"])
for seller_id, seller in enumerate(["A", "B", "C", "D", "E"]):

    df_test.seller = df_test.seller.str.replace(seller, f"{seller_id}")
    df_test.buyer = df_test.buyer.str.replace(seller, f"{seller_id}")

df_test.seller = df_test.seller.astype(int)
df_test.buyer = df_test.buyer.astype(int)
df_test = df_test.reset_index().rename(columns={"index": "time"})
df_test["price"] = 10
df_test["size"] = 10
df_test["time"] = df_test.time.apply(lambda x: datetime.datetime.now() + datetime.timedelta(seconds=x))

In [ ]:
from src.DataReformator import prepare_postmerge_csv

prepare_postmerge_csv(
    df_test,
    out_csv="test.csv",
    token_id="AVAX",
    token_usd_const=30,     # constant token USD price (your quick method)
    eth_usd_const=3500.0,     # optional: to also compute token_price_in_eth & trade_amount_eth
    price_is_token_in_eth=False,  # set True only if you want to take per-row df['price'] as token-in-ETH
)

In [ ]:
# compatibility

In [ ]:
from src.data_handler import CoinDataStore
from src.DataReformator import prepare_postmerge_csv

token = "AVAX"
store = CoinDataStore(token, engine="fastparquet")
df_trades = store.load_all()

prepare_postmerge_csv(
    df_trades,
    out_csv=f"{token}_compatible_trades.csv",
    token_id=token,
    token_usd_const=1,     # constant token USD price (your quick method)
    eth_usd_const=3500.0,     # optional: to also compute token_price_in_eth & trade_amount_eth
    price_is_token_in_eth=False,  # set True only if you want to take per-row df['price'] as token-in-ETH
)